// AUTO-GENERATED by scripts/build-images.js — do not edit by hand.
// Regenerate with `npm run images`.

export interface ImageMeta {
	width: number;
	height: number;
	ratio: number;
	widths: number[];
	fallback: number;
}

export const images = {
	"team-2025": {
		"width": 2400,
		"height": 1109,
		"ratio": 2.1641,
		"widths": [
			640,
			1024,
			1600,
			2400
		],
		"fallback": 2400
	},
	"win-2025": {
		"width": 1868,
		"height": 1048,
		"ratio": 1.7824,
		"widths": [
			640,
			1024,
			1600
		],
		"fallback": 1600
	},
	"rocketleague": {
		"width": 1874,
		"height": 1062,
		"ratio": 1.7646,
		"widths": [
			640,
			1024,
			1600
		],
		"fallback": 1600
	},
	"flex-rlbot": {
		"width": 1910,
		"height": 1100,
		"ratio": 1.7364,
		"widths": [
			640,
			1024,
			1600
		],
		"fallback": 1600
	},
	"quiz-2025": {
		"width": 1910,
		"height": 1100,
		"ratio": 1.7364,
		"widths": [
			640,
			1024,
			1600
		],
		"fallback": 1600
	},
	"win-2022": {
		"width": 2400,
		"height": 1800,
		"ratio": 1.3333,
		"widths": [
			640,
			1024,
			1600
		],
		"fallback": 1600
	},
	"seminar": {
		"width": 1440,
		"height": 1080,
		"ratio": 1.3333,
		"widths": [
			640,
			1024,
			1440
		],
		"fallback": 1440
	},
	"wiki": {
		"width": 2400,
		"height": 1800,
		"ratio": 1.3333,
		"widths": [
			640,
			1024,
			1600
		],
		"fallback": 1600
	}
} as const satisfies Record<string, ImageMeta>;

export type ImageName = keyof typeof images;
